# Generated by Django 3.2.9 on 2021-12-03 22:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('client_id', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=10)),
                ('viber', models.BooleanField(default=False)),
                ('telegram', models.BooleanField(default=False)),
                ('reserve_phone', models.CharField(blank=True, max_length=10)),
                ('housing_complex', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=25)),
                ('town', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=20)),
                ('building', models.IntegerField()),
                ('house_building', models.IntegerField(blank=True)),
                ('flat', models.IntegerField()),
                ('communal_service', models.BooleanField(default=False)),
                ('communal_service_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('water', models.BooleanField(default=False)),
                ('water_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('electricity', models.BooleanField(default=False)),
                ('electricity_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.IntegerField(choices=[(0, 'Нарахування'), (1, 'Оплата')])),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('appointment', models.IntegerField(choices=[(0, 'Комунальний сервіс'), (1, 'Водопостачання'), (2, 'Електропостачання')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 12, 4, 0, 12, 41, 628492))),
                ('type', models.IntegerField(choices=[(0, 'Водопостачання'), (1, 'Електроенергія')])),
                ('value', models.CharField(default=0, max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.client')),
            ],
        ),
    ]
