# Generated by Django 3.2.9 on 2021-12-03 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 0, 17, 8, 105553)),
        ),
    ]
