# Generated by Django 3.2.9 on 2022-01-06 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 16, 27, 1, 324127)),
        ),
        migrations.AlterField(
            model_name='task',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='service.master'),
        ),
    ]
