# Generated by Django 3.2.9 on 2022-01-06 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220106_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='master',
        ),
        migrations.AlterField(
            model_name='counter',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 16, 31, 12, 280365)),
        ),
    ]
