# Generated by Django 3.2.9 on 2022-01-08 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 15, 34, 53, 15667)),
        ),
    ]
