# Generated by Django 3.2.9 on 2022-01-08 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_counter_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='time',
        ),
        migrations.AlterField(
            model_name='counter',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 15, 45, 12, 2796)),
        ),
    ]
