# Generated by Django 3.2.9 on 2022-01-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('staff_full_name', models.CharField(default='ПІБ', max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('department', models.IntegerField(choices=[(0, 'Комунальний сервіс'), (1, 'Сантехніка'), (2, 'Електрика')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
        ),
    ]
