# Generated by Django 3.2.9 on 2022-01-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=120)),
                ('contact_person', models.CharField(max_length=60)),
            ],
        ),
    ]
