# Generated by Django 3.2.9 on 2022-01-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='staff_full_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
    ]
